Importing CSV

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\engenharia de dados\curso udemy\Arquivos\04.+ETL+Pandas\04. ETL Pandas\arquivos_csv\Clientes.csv", delimiter=',')

In [4]:
estado = df.loc[df['state'] == 'Mato Grosso']

In [ ]:
'''df = df.loc[df['state'] == 'São Paulo']
df.head(2)'''

In [5]:
DF_estados = df.loc[df['state'].isin(['Rio de Janeiro', 'Ceará', 'Rondônia', 'Bahia'])]

In [7]:
df.head(30)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,NaN,9 9102-7834,Brasil,Acre,NaN,NaN,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,NaN,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,NaN
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,NaN,NaN,NaN
4,4,2018-08-06 07:24:16,Romário,Teixeira,NaN,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,NaN,9 2830-2088,Brasil,Rio Grande do Sul,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goiás,Rua 78 do Estado Goiás,877.0,Apto 14
7,7,2018-02-08 12:36:09,Everton,Barbosa,everton@meu_email.com,9 2553-4087,Brasil,Distrito Federal,Avenida 86 do Estado Distrito Federal,864.0,Apto 14
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,NaN,NaN,NaN
9,9,2018-11-11 11:48:41,Luan,Dias,luan@exemplo.com,9 2417-3678,Brasil,Distrito Federal,Avenida 54 do Estado Distrito Federal,889.0,Conjunto 14
10,10,2017-12-16 15:41:00,Mariana,Alves,mariana@meu_email.com,9 1846-6377,Brasil,Santa Catarina,NaN,NaN,NaN
11,11,2018-05-16 03:39:52,James,Albuquerque,NaN,9 2430-5905,Brasil,Sergipe,Rua 30 do Estado Sergipe,229.0,NaN
12,12,2018-03-28 00:24:00,Carol,Barboza,carol@exemplo.com,9 8487-3501,Brasil,Mato Grosso,Rua 31 do Estado Mato Grosso,1.0,Conjunto 23
13,13,2018-08-27 21:15:17,Carolina,Monteiro,carolina@teste.com,9 1226-4267,Brasil,Rio Grande do Sul,Rua 4 do Estado Rio Grande do Sul,444.0,Apto 21
14,14,2017-11-12 03:02:41,Francisco,Nascimento,francisco@exemplo.com,9 7264-9020,Brasil,Distrito Federal,Rua 75 do Estado Distrito Federal,47.0,NaN
15,15,2018-11-15 18:00:53,Stephanie,Barbosa,stephanie@usuario.com,9 1446-3560,Brasil,Mato Grosso,NaN,NaN,Conjunto 4
16,16,2017-12-12 21:29:54,Laura,Santos,laura@exemplo.com,9 7802-6152,Brasil,Maranhão,Rua 57 do Estado Maranhão,213.0,NaN
17,17,2017-10-19 20:18:14,João,Magalhães,joão@exemplo.com,9 5995-1272,Brasil,Pernambuco,Rua 20 do Estado Pernambuco,781.0,Apto 17
18,18,2018-06-28 04:53:52,Jair,Magalhães,jair@exemplo.com,9 8368-1315,Brasil,Alagoas,Avenida 74 do Estado Alagoas,118.0,Conjunto 8
19,19,2018-10-20 19:31:52,Caíque,Monteiro,caíque@exemplo.com,9 9793-9986,Brasil,Piauí,NaN,NaN,Conjunto 13
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,São Paulo,Rua 57 do Estado São Paulo,851.0,Conjunto 20
21,21,2018-02-21 15:35:55,Diego,Freire,diego@teste.com,9 6686-4094,Brasil,Bahia,Praça 4 do Estado Bahia,906.0,Apto 20
22,22,2018-04-18 22:43:29,Heitor,Pereira,NaN,9 4839-8118,Brasil,Maranhão,Avenida 84 do Estado Maranhão,948.0,NaN
23,23,2017-10-26 00:35:22,Maria,Pires,NaN,9 8229-1067,Brasil,Amazonas,Avenida 80 do Estado Amazonas,581.0,NaN
24,24,2018-07-25 09:34:12,Jair,Barroso,jair@teste.com,9 6679-6120,Brasil,Ceará,Rua 86 do Estado Ceará,770.0,Apto 21
25,25,2018-08-07 12:22:40,Alice,Veloso,alice@exemplo.com,9 9869-3706,Brasil,Minas Gerais,Praça 73 do Estado Minas Gerais,571.0,NaN
26,26,2018-12-12 11:56:14,Eloá,da Silva,eloá@usuario.com,9 3982-5948,Brasil,Espírito Santo,Avenida 98 do Estado Espírito Santo,706.0,NaN
27,27,2018-11-08 11:12:47,Luan,Lima,luan@teste.com,9 2529-8197,Brasil,Acre,Praça 86 do Estado Acre,303.0,Apto 27
28,28,2017-11-26 05:17:39,Beatriz,Araújo,beatriz@usuario.com,9 4543-3853,Brasil,Minas Gerais,Praça 7 do Estado Minas Gerais,536.0,Conjunto 5
29,29,2018-06-03 17:08:52,Geisa,Santos,geisa@meu_email.com,9 4653-9739,Brasil,Rio Grande do Norte,Avenida 77 do Estado Rio Grande do Norte,486.0,Conjunto 13

Handling Null data

In [14]:
df['street'] = df['street'].fillna('Nao Registrado')
df['email'] = df['email'].fillna('Email Não Cadastrado')
df['number'] = df['number'].fillna('Sem numero')
df['additionals'] = df['additionals'].fillna('Sem Info')
df.head(3)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Cadastrado,9 9102-7834,Brasil,Acre,Nao Registrado,Sem numero,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Cadastrado,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,São Paulo,Avenida 59 do Estado São Paulo,534.0,Sem registro

Replace method

In [15]:
df['state'] = df['state'].replace('São Paulo', 'Sao Paulo')
df.head(3)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Cadastrado,9 9102-7834,Brasil,Acre,Nao Registrado,Sem numero,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Cadastrado,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,Sao Paulo,Avenida 59 do Estado São Paulo,534.0,Sem registro

In [16]:
valor_original = 'Sao Paulo'
valor_substituto = 'SP'
df['state'] = df['state'].replace(valor_original, valor_substituto)
df.head(3)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Cadastrado,9 9102-7834,Brasil,Acre,Nao Registrado,Sem numero,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Cadastrado,9 7328-8718,Brasil,Rio Grande do Sul,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,SP,Avenida 59 do Estado São Paulo,534.0,Sem registro

In [21]:
df['state'] = df['state'].replace('Acre', 'AC')
df['state'] = df['state'].replace('Rio Grande do Sul', 'RN')
df.head(3)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Cadastrado,9 9102-7834,Brasil,AC,Nao Registrado,Sem numero,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Cadastrado,9 7328-8718,Brasil,RN,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,SP,Avenida 59 do Estado São Paulo,534.0,Sem registro

In [22]:
mapeamento = {'Maranhão' : 'Maranhao', 'Piauí' : 'Piaui', 'Goiás' : 'Goias'}
df['state'] = df['state'].replace(mapeamento)
df.head(30)

,id,created_at,first_name,last_name,email,cell_phone,country,state,street,number,additionals
0,0,2017-11-01 14:45:41,Marta,Jesus,Email Não Cadastrado,9 9102-7834,Brasil,AC,Nao Registrado,Sem numero,Conjunto 16
1,1,2017-10-16 00:50:39,Luana,Almeida,Email Não Cadastrado,9 7328-8718,Brasil,RN,Avenida 56 do Estado Rio Grande do Sul,989.0,Conjunto 17
2,2,2018-06-16 17:51:29,Frida,Mendes,frida@meu_email.com,9 5906-7552,Brasil,SP,Avenida 59 do Estado São Paulo,534.0,Sem registro
3,3,2018-01-17 03:02:58,Daniela,Avelino,daniela@exemplo.com,9 4642-9486,Brasil,Mato Grosso,Nao Registrado,Sem numero,Sem registro
4,4,2018-08-06 07:24:16,Romário,Teixeira,Email Não Cadastrado,9 3093-6522,Brasil,Bahia,Praça 56 do Estado Bahia,191.0,Apto 12
5,5,2018-01-05 17:20:49,Marcelo,Barroso,Email Não Cadastrado,9 2830-2088,Brasil,RN,Rua 28 do Estado Rio Grande do Sul,805.0,Conjunto 13
6,6,2018-06-18 11:17:42,Cristiano,Elísio,cristiano@exemplo.com,9 3532-8404,Brasil,Goias,Rua 78 do Estado Goiás,877.0,Apto 14
7,7,2018-02-08 12:36:09,Everton,Barbosa,everton@meu_email.com,9 2553-4087,Brasil,Distrito Federal,Avenida 86 do Estado Distrito Federal,864.0,Apto 14
8,8,2017-12-16 20:47:03,Gabriela,Alves,gabriela@exemplo.com,9 1353-8433,Brasil,Santa Catarina,Nao Registrado,Sem numero,Sem registro
9,9,2018-11-11 11:48:41,Luan,Dias,luan@exemplo.com,9 2417-3678,Brasil,Distrito Federal,Avenida 54 do Estado Distrito Federal,889.0,Conjunto 14
10,10,2017-12-16 15:41:00,Mariana,Alves,mariana@meu_email.com,9 1846-6377,Brasil,Santa Catarina,Nao Registrado,Sem numero,Sem registro
11,11,2018-05-16 03:39:52,James,Albuquerque,Email Não Cadastrado,9 2430-5905,Brasil,Sergipe,Rua 30 do Estado Sergipe,229.0,Sem registro
12,12,2018-03-28 00:24:00,Carol,Barboza,carol@exemplo.com,9 8487-3501,Brasil,Mato Grosso,Rua 31 do Estado Mato Grosso,1.0,Conjunto 23
13,13,2018-08-27 21:15:17,Carolina,Monteiro,carolina@teste.com,9 1226-4267,Brasil,RN,Rua 4 do Estado Rio Grande do Sul,444.0,Apto 21
14,14,2017-11-12 03:02:41,Francisco,Nascimento,francisco@exemplo.com,9 7264-9020,Brasil,Distrito Federal,Rua 75 do Estado Distrito Federal,47.0,Sem registro
15,15,2018-11-15 18:00:53,Stephanie,Barbosa,stephanie@usuario.com,9 1446-3560,Brasil,Mato Grosso,Nao Registrado,Sem numero,Conjunto 4
16,16,2017-12-12 21:29:54,Laura,Santos,laura@exemplo.com,9 7802-6152,Brasil,Maranhao,Rua 57 do Estado Maranhão,213.0,Sem registro
17,17,2017-10-19 20:18:14,João,Magalhães,joão@exemplo.com,9 5995-1272,Brasil,Pernambuco,Rua 20 do Estado Pernambuco,781.0,Apto 17
18,18,2018-06-28 04:53:52,Jair,Magalhães,jair@exemplo.com,9 8368-1315,Brasil,Alagoas,Avenida 74 do Estado Alagoas,118.0,Conjunto 8
19,19,2018-10-20 19:31:52,Caíque,Monteiro,caíque@exemplo.com,9 9793-9986,Brasil,Piaui,Nao Registrado,Sem numero,Conjunto 13
20,20,2017-12-22 10:51:28,Adalberto,Silva,adalberto@usuario.com,9 1338-1447,Brasil,SP,Rua 57 do Estado São Paulo,851.0,Conjunto 20
21,21,2018-02-21 15:35:55,Diego,Freire,diego@teste.com,9 6686-4094,Brasil,Bahia,Praça 4 do Estado Bahia,906.0,Apto 20
22,22,2018-04-18 22:43:29,Heitor,Pereira,Email Não Cadastrado,9 4839-8118,Brasil,Maranhao,Avenida 84 do Estado Maranhão,948.0,Sem registro
23,23,2017-10-26 00:35:22,Maria,Pires,Email Não Cadastrado,9 8229-1067,Brasil,Amazonas,Avenida 80 do Estado Amazonas,581.0,Sem registro
24,24,2018-07-25 09:34:12,Jair,Barroso,jair@teste.com,9 6679-6120,Brasil,Ceará,Rua 86 do Estado Ceará,770.0,Apto 21
25,25,2018-08-07 12:22:40,Alice,Veloso,alice@exemplo.com,9 9869-3706,Brasil,Minas Gerais,Praça 73 do Estado Minas Gerais,571.0,Sem registro
26,26,2018-12-12 11:56:14,Eloá,da Silva,eloá@usuario.com,9 3982-5948,Brasil,Espírito Santo,Avenida 98 do Estado Espírito Santo,706.0,Sem registro
27,27,2018-11-08 11:12:47,Luan,Lima,luan@teste.com,9 2529-8197,Brasil,AC,Praça 86 do Estado Acre,303.0,Apto 27
28,28,2017-11-26 05:17:39,Beatriz,Araújo,beatriz@usuario.com,9 4543-3853,Brasil,Minas Gerais,Praça 7 do Estado Minas Gerais,536.0,Conjunto 5
29,29,2018-06-03 17:08:52,Geisa,Santos,geisa@meu_email.com,9 4653-9739,Brasil,Rio Grande do Norte,Avenida 77 do Estado Rio Grande do Norte,486.0,Conjunto 13